POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Movie",
  "description": "Movie description"
}

###
GET http://localhost:3000/categories/20d4ac2d-63ca-4112-b691-d12129f13325

###
POST http://localhost:3000/cast-members
Content-Type: application/json

{
  "name": "Raphael",
  "type": 2
}

###
PATCH http://localhost:3000/cast-members/26a1a65a-aff0-43c8-b917-87bb971db143
Content-Type: application/json

{
  "name": "Peter Parker"
}

###
DELETE http://localhost:3000/cast-members/2b7ca739-864a-4a7a-b9b7-080349085141
Content-Type: application/json

{
  "name": "Raphael",
  "type": 2
}

###
GET http://localhost:3000/cast-members?type=2
Content-Type: application/json